-- Optional seed data for Hermes Operations HQ.
-- Run after supabase/hermes_workspaces.sql if you want the internal console
-- to start with our known non-secret operating records.
--
-- This file stores operator metadata only. Do NOT add bot tokens, API keys,
-- passwords, cookies, OAuth refresh tokens, or .env contents here.

insert into public.hermes_workspaces (
  client_name,
  workspace_key,
  workspace_type,
  organization,
  purpose,
  environment,
  isolation_model,
  vps_hostname,
  hermes_profile,
  profile_path,
  service_name,
  dashboard_url,
  dashboard_port,
  discord_bot_name,
  discord_server_name,
  discord_channel_name,
  discord_channel_id,
  status,
  support_status,
  checklist_profile_exists,
  checklist_dashboard_running,
  checklist_discord_connected,
  checklist_message_content_intent_on,
  checklist_service_restarted,
  checklist_test_message_passed,
  notes
)
values
  (
    'connectNPO Hermes Operations HQ',
    'connectnpo-hermes-ops-hq',
    'internal',
    'connectnpo',
    'dashboard',
    'internal',
    'shared_vps_profile',
    null,
    'default',
    '/root/.hermes',
    null,
    null,
    null,
    'NPOBot',
    'NPOBot',
    '#general',
    '1506413921702248460',
    'active',
    'monitoring',
    true,
    true,
    true,
    true,
    true,
    true,
    'Internal command center for managing connectNPO, GivingArc, Wife CPA, staff, and future client Hermes workspaces. This should be proven internally before a customer-facing dashboard is split out.'
  ),
  (
    'connectNPO ContentBot',
    'connectnpo-contentbot',
    'internal',
    'connectnpo',
    'content',
    'internal',
    'shared_vps_profile',
    null,
    'connectnpo-content',
    '/root/.hermes/profiles/connectnpo-content',
    'hermes-gateway-connectnpo-content.service',
    null,
    null,
    'ContentBot#0838',
    'NPOBot',
    '#general',
    '1507203008482771054',
    'active',
    'monitoring',
    true,
    false,
    true,
    true,
    true,
    true,
    'Content workspace for connectNPO public-facing and operations content. Google OAuth default is info@connectnpo.com; never store OAuth tokens here.'
  ),
  (
    'GivingArc Meeting Intelligence',
    'givingarc-meeting-intel',
    'internal',
    'givingarc',
    'meeting_intel',
    'internal',
    'shared_vps_profile',
    null,
    'givingarc-meeting-intel',
    '/root/.hermes/profiles/givingarc-meeting-intel',
    null,
    null,
    null,
    'MeetingIntelBot#9997',
    'Giving Arc',
    '#meeting-intel',
    '1515970894001082378',
    'active',
    'monitoring',
    true,
    false,
    true,
    true,
    true,
    true,
    'Private Giving Arc meeting research and transcript intelligence workspace. Keep it isolated from connectNPO and CPA/accounting contexts.'
  ),
  (
    'GivingArc Content',
    'givingarc-content',
    'internal',
    'givingarc',
    'content',
    'internal',
    'shared_vps_profile',
    null,
    'givingarc-content',
    '/root/.hermes/profiles/givingarc-content',
    null,
    null,
    null,
    'Arcbot',
    'Giving Arc',
    '#general',
    null,
    'active',
    'monitoring',
    true,
    false,
    true,
    true,
    true,
    true,
    'Giving Arc content workspace. Keep separate from CPA/tax/Form 990 work.'
  ),
  (
    'Wife CPA Nonprofit Accounting',
    'wife-cpa-accounting',
    'internal',
    'wife_cpa',
    'accounting',
    'internal',
    'shared_vps_profile',
    null,
    'wife-cpa',
    '/root/.hermes/profiles/wife-cpa',
    null,
    null,
    null,
    'CPATaxBot',
    'Giving Arc',
    '#nonprofit-accounting',
    null,
    'setup',
    'needs_setup',
    false,
    false,
    false,
    true,
    false,
    false,
    'Nonprofit CPA/accounting/tax/Form 990 workspace. Keep it isolated from Giving Arc content and connectNPO data.'
  )
on conflict (workspace_key) do update set
  client_name = excluded.client_name,
  workspace_type = excluded.workspace_type,
  organization = excluded.organization,
  purpose = excluded.purpose,
  environment = excluded.environment,
  isolation_model = excluded.isolation_model,
  vps_hostname = excluded.vps_hostname,
  hermes_profile = excluded.hermes_profile,
  profile_path = excluded.profile_path,
  service_name = excluded.service_name,
  dashboard_url = excluded.dashboard_url,
  dashboard_port = excluded.dashboard_port,
  discord_bot_name = excluded.discord_bot_name,
  discord_server_name = excluded.discord_server_name,
  discord_channel_name = excluded.discord_channel_name,
  discord_channel_id = excluded.discord_channel_id,
  status = excluded.status,
  support_status = excluded.support_status,
  checklist_profile_exists = excluded.checklist_profile_exists,
  checklist_dashboard_running = excluded.checklist_dashboard_running,
  checklist_discord_connected = excluded.checklist_discord_connected,
  checklist_message_content_intent_on = excluded.checklist_message_content_intent_on,
  checklist_service_restarted = excluded.checklist_service_restarted,
  checklist_test_message_passed = excluded.checklist_test_message_passed,
  notes = excluded.notes;
